[theme]
base = "dark"
primaryColor = "#10b981"
backgroundColor = "#0e131f"
secondaryBackgroundColor = "#171e2e"
textColor = "#f3f4f6"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
